name: Publish nightly builds 

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release /p:PatchNumber=$GITHUB_RUN_NUMBER-nightly
    - name: Collect packages
      run: |
        mkdir artifacts
        cp Config.Numerge.json artifacts/
        mkdir -p artifacts/input/
        find . -name \*.nupkg -exec cp {} artifacts/input/ \;
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/
  numerge:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Numerge
        uses: actions/checkout@v2.3.4
        with:
          repository: CreateLab/Numerge
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.*
      - name: Build Numerge
        run: dotnet build
      - name: Download packages
        uses: actions/download-artifact@v2.0.8
        with:
          name: artifacts
          path: artifacts
      - name: Merge packages
        run: |
          mkdir artifacts/output/
          dotnet run --project Numerge.Console artifacts/Config.Numerge.json artifacts/input/ artifacts/output/
      - name: Publish to Nuget
        run: dotnet nuget push "artifacts/output/Material.Avalonia.*.nupkg" --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish to GitHub Packages
        run: dotnet nuget push "artifacts/output/Material.Avalonia.*.nupkg" --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/AvaloniaCommunity/index.json --skip-duplicate